spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:studyhub
    username: sa
    password:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        hibernate:
          format_sql: true


logging.level:
  org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: V32xDI46noTAyFEbxqvaYTclk71dKTlGMCO5wqpUZo8f8kvEssHec6G1WEJqODZ8yEPXvh6P8GMWUCfguKypMg==
  # 변경 필요