spring:
  profiles:
    group:
      dev: default,h2,log
      prod: default
    default: dev
---
spring:
  config:
    activate:
      on-profile: default
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

jwt:
  secret: V32xDI46noTAyFEbxqvaYTclk71dKTlGMCO5wqpUZo8f8kvEssHec6G1WEJqODZ8yEPXvh6P8GMWUCfguKypMg==

---
spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:studyhub
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: log
logging:
  level:
    p6spy: INFO
