spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:studyhub
    username: sa
    password:
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    p6spy: INFO

jwt:
  secret: V32xDI46noTAyFEbxqvaYTclk71dKTlGMCO5wqpUZo8f8kvEssHec6G1WEJqODZ8yEPXvh6P8GMWUCfguKypMg==
  # 변경 필요