### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "leyng7",
  "password": "1q2w3e4r!",
  "nickname": "몽친"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "leyng7",
  "password": "1q2w3e4r!"
}

### 재발급
POST http://localhost:8080/api/auth/reissue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxMjg0NTA5MX0.bLDx14XtVAumMi_rvW_HbM1E76XI6TSmUvhax0_Q-3pZEM-4Tv4GG59y1L5ajomM2HT0vdyfJahDsYKCfmELrg
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MTM0NDgwOTF9.7RqlcJiDI7kSBAI10xH98n_a6DMTxTMF2ZD1suUXlTA9BPsLpJWoVR_nFB6LuQVf8_k14l31tb2NwDIhCdhCSA"
}