### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "leyng7",
  "password": "1q2w3e4r!",
  "nickname": "몽친"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "leyng7",
  "password": "1q2w3e4r!"
}

### 재발급
POST http://localhost:8080/api/auth/reissue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxMjg5MDU5NX0.UkAQtWqFX2hShnV1RIek0wLV2TUVKHpu9jLYpHMOhMtADaOcYZ5pOvfw_rlWpYybKqicGnHj3rT7FtHp9Czzdw
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MTM0NDgwOTF9.7RqlcJiDI7kSBAI10xH98n_a6DMTxTMF2ZD1suUXlTA9BPsLpJWoVR_nFB6LuQVf8_k14l31tb2NwDIhCdhCSA"
}

### 탈퇴
DELETE http://localhost:8080/api/members/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTcxMjg5MTUzNn0.KhcehniEw0oroW_adH-mph6_RLe1yk6_MsnwlBg40XRjMhLCvhjw1mop-vVeTD5JRUJqikxvwSMObXU6KKrA0A
Content-Type: application/json

{}